#!/usr/bin/env python3
"""Precision-recall view of every PQC-versus-MLP head comparison.

For each cell of Table stats_paired_v9 this script reports, per head and
averaged over seeds, the area under the precision-recall curve (average
precision, AP) computed from the stored per-example logits and labels, the
test positive base rate (the AP of a label-independent scorer), and the
class-wise precision and recall at the zero threshold used by the trainer.
The paired difference in AP is tested with a paired t-test.

Run from the repository root: python scripts/metrics_prc_v9.py
Writes results/metrics_prc_v9.json and paper/table_prc_v9.tex.
"""
from __future__ import annotations

import glob
import json
import os
import re
import sys
from collections import defaultdict

import numpy as np
from scipy import stats
from sklearn.metrics import average_precision_score

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) if "scripts" in os.path.abspath(__file__) else os.getcwd()
if len(sys.argv) > 1:
    ROOT = sys.argv[1]


def load(paths):
    runs = defaultdict(lambda: defaultdict(dict))
    for f in paths:
        m = re.match(r"^hybrid_(v\d+)_", os.path.basename(f))
        if not m:
            continue
        d = json.load(open(f))
        c = d["config"]
        if c.get("n_layers", 2) != 2 or c["head"] not in ("pqc", "mlp"):
            continue
        runs[(m.group(1), c["task"], c["reducer"], c["n_qubits"])][c["head"]][c["seed"]] = d
    return runs


def head_metrics(r):
    y = np.asarray(r["test_labels"], int)
    z = np.asarray(r["test_logits"], float)
    p = (z > 0).astype(int)
    tp, fp = int(((p == 1) & (y == 1)).sum()), int(((p == 1) & (y == 0)).sum())
    fn, tn = int(((p == 0) & (y == 1)).sum()), int(((p == 0) & (y == 0)).sum())
    t = r["phase2"]["test"]
    assert (tp, fp, fn, tn) == (int(t["tp"]), int(t["fp"]), int(t["fn"]), int(t["tn"])), "confusion matrix does not match the stored one"
    div = lambda a, b: a / b if b > 0 else 0.0
    return {
        "ap": float(average_precision_score(y, z)),
        "base_rate": float(y.mean()),
        "prec_pos": div(tp, tp + fp), "rec_pos": div(tp, tp + fn),
        "prec_neg": div(tn, tn + fn), "rec_neg": div(tn, tn + fp),
        "auc": float(t["auc"]),
    }


def cell_stats(pqc, mlp, seeds):
    for s in seeds:
        assert pqc[s]["test_labels"] == mlp[s]["test_labels"]
    P = [head_metrics(pqc[s]) for s in seeds]
    M = [head_metrics(mlp[s]) for s in seeds]
    out = {"n": len(seeds), "base_rate": float(np.mean([x["base_rate"] for x in P]))}
    for k in ("ap", "prec_pos", "rec_pos", "prec_neg", "rec_neg", "auc"):
        a, b = np.array([x[k] for x in P]), np.array([x[k] for x in M])
        out[f"pqc_{k}"], out[f"pqc_{k}_sd"] = float(a.mean()), float(a.std(ddof=1))
        out[f"mlp_{k}"], out[f"mlp_{k}_sd"] = float(b.mean()), float(b.std(ddof=1))
        out[f"delta_{k}"] = float((b - a).mean())
        out[f"paired_t_p_{k}"] = float(stats.ttest_rel(b, a).pvalue)
    return out


def main():
    primary = load(sorted(glob.glob(os.path.join(ROOT, "results/v4/*.json"))) + sorted(glob.glob(os.path.join(ROOT, "results/v5/*.json"))))
    posthoc = load(sorted(glob.glob(os.path.join(ROOT, "results/v8/*q16both*.json"))))
    rows = []
    for key in sorted(primary):
        h = primary[key]
        if "pqc" in h and "mlp" in h:
            seeds = sorted(set(h["pqc"]) & set(h["mlp"]))
            rows.append({"version": key[0], "task": key[1], "reducer": key[2], "n_qubits": key[3], "family": "primary", **cell_stats(h["pqc"], h["mlp"], seeds)})
    h = primary[("v5", "paws", "depthwise", 8)]
    rows.append({"version": "v5", "task": "paws", "reducer": "depthwise", "n_qubits": 8, "family": "pre-specified-8-seed", **cell_stats(h["pqc"], h["mlp"], list(range(8)))})
    for key in sorted(posthoc):
        h = posthoc[key]
        seeds = sorted(set(h["pqc"]) & set(h["mlp"]))
        rows.append({"version": "v8", "task": key[1], "reducer": key[2], "n_qubits": key[3], "family": "post hoc q=16", **cell_stats(h["pqc"], h["mlp"], seeds)})
    os.makedirs(os.path.join(ROOT, "results"), exist_ok=True)
    os.makedirs(os.path.join(ROOT, "paper"), exist_ok=True)
    json.dump(rows, open(os.path.join(ROOT, "results/metrics_prc_v9.json"), "w"), indent=1)

    task = {"mrpc": r"\MRPC{}", "paws": r"\PAWS{}", "qqp": r"\QQP{}"}
    lines = [
        "%% Auto-generated by scripts/metrics_prc_v9.py -- do not hand-edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Precision-recall view of the head comparisons of Table~\ref{tab:paired_v9}, computed from the stored per-example logits and labels. AP is the area under the precision-recall curve (average precision); $p$ is the test positive base rate, which is the AP of a label-independent scorer, so AP $- p$ is the precision-recall counterpart of AUC $- 0.5$. $\Delta$AP is \MLP{} minus \PQC{} with a paired $t$-test over seeds. P$^{+}$, R$^{+}$, P$^{-}$ and R$^{-}$ are precision and recall of the positive and negative classes at the zero threshold used for every thresholded metric in this paper; all entries are means over seeds. The pre-specified 8-seed \PAWS{} cell and the two post hoc $q = 16$ cells are listed below the rule.}",
        r"\label{tab:prc_v9}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lllcc|cccc|cccc|cccc}",
        r"\toprule",
        r" & & & & & \multicolumn{4}{c|}{Precision-recall area} & \multicolumn{4}{c|}{\PQC{}} & \multicolumn{4}{c}{\MLP{}} \\",
        r"Task & Reducer & Ver & $q$ & $p$ & AP \PQC{} & AP \MLP{} & $\Delta$AP & paired $p$ & P$^{+}$ & R$^{+}$ & P$^{-}$ & R$^{-}$ & P$^{+}$ & R$^{+}$ & P$^{-}$ & R$^{-}$ \\",
        r"\midrule",
    ]
    for r in rows:
        if r["family"] == "pre-specified-8-seed":
            lines.append(r"\midrule")
        ver = "v5 (8 s.)" if r["family"] == "pre-specified-8-seed" else r["version"]
        lines.append(
            f'{task[r["task"]]} & {r["reducer"]} & {ver} & {r["n_qubits"]} & {r["base_rate"]:.3f} & '
            f'{r["pqc_ap"]:.3f} & {r["mlp_ap"]:.3f} & {r["delta_ap"]:+.3f} & {r["paired_t_p_ap"]:.4f} & '
            f'{r["pqc_prec_pos"]:.3f} & {r["pqc_rec_pos"]:.3f} & {r["pqc_prec_neg"]:.3f} & {r["pqc_rec_neg"]:.3f} & '
            f'{r["mlp_prec_pos"]:.3f} & {r["mlp_rec_pos"]:.3f} & {r["mlp_prec_neg"]:.3f} & {r["mlp_rec_neg"]:.3f} \\\\'
        )
    lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
    open(os.path.join(ROOT, "paper/table_prc_v9.tex"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    for r in rows:
        print(f'{r["version"]:<3} {r["task"]:<5} {r["reducer"]:<10} q{r["n_qubits"]:<3} n{r["n"]:<3} {r["family"]:<20} p {r["base_rate"]:.3f} '
              f'AP pqc {r["pqc_ap"]:.3f} mlp {r["mlp_ap"]:.3f} dAP {r["delta_ap"]:+.3f} (p {r["paired_t_p_ap"]:.4f}) '
              f'| PQC P+ {r["pqc_prec_pos"]:.3f} R+ {r["pqc_rec_pos"]:.3f} P- {r["pqc_prec_neg"]:.3f} R- {r["pqc_rec_neg"]:.3f} '
              f'| MLP P+ {r["mlp_prec_pos"]:.3f} R+ {r["mlp_rec_pos"]:.3f} P- {r["mlp_prec_neg"]:.3f} R- {r["mlp_rec_neg"]:.3f} '
              f'| AUC {r["pqc_auc"]:.3f} {r["mlp_auc"]:.3f}')
    print("wrote results/metrics_prc_v9.json and paper/table_prc_v9.tex")


if __name__ == "__main__":
    main()
