#!/usr/bin/env python3
"""Reviewer-requested effective-parameter-matched MLP control.

Compares the calibrated PQC (24 output-relevant parameters: 22 circuit +
2 affine) with a calibrated MLP of hidden width 2 (23 trainable parameters)
on MRPC, PAWS and QQP.  Reports paired seed-level statistics, a three-test
Holm correction, item-clustered inference and precision-recall area.

Writes results/stats_effective_match_v10.json and
paper/table_effective_match_v10.tex.
"""
from __future__ import annotations

import glob
import json
import os
import sys

import numpy as np
from scipy import stats
from sklearn.metrics import average_precision_score

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if len(sys.argv) > 1:
    ROOT = os.path.abspath(sys.argv[1])
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from stats_example_level_v9 import cell as item_cell  # noqa: E402

N_BOOT = 10_000


def load(pattern):
    out = {}
    for path in glob.glob(os.path.join(ROOT, pattern)):
        run = json.load(open(path))
        out[run["config"]["seed"]] = run
    return out


def holm(pvalues):
    pvalues = np.asarray(pvalues, float)
    order = np.argsort(pvalues)
    adjusted = np.empty(len(pvalues))
    running = 0.0
    for rank, idx in enumerate(order):
        running = max(running, (len(pvalues) - rank) * pvalues[idx])
        adjusted[idx] = min(1.0, running)
    return adjusted


def paired_ci(delta, seed=0):
    rng = np.random.default_rng(seed)
    samples = rng.choice(delta, size=(N_BOOT, len(delta)), replace=True).mean(1)
    return [float(x) for x in np.percentile(samples, [2.5, 97.5])]


def main():
    rows = []
    for task in ("mrpc", "paws", "qqp"):
        pqc = load(f"results/v5/hybrid_v5_{task}_depthwise_pqc_q8_l2_s*.json")
        mlp = load(f"results/v9/hybrid_v9_{task}_depthwise_mlp_effmatch_h2_q8_l2_s*.json")
        baseline = load(f"results/v5/hybrid_v5_{task}_depthwise_mlp_q8_l2_s*.json")
        seeds = sorted(set(pqc) & set(mlp) & set(baseline))[:8]
        assert seeds == list(range(8)), (task, seeds)

        pf = np.array([pqc[s]["phase2"]["test"]["macro_f1"] for s in seeds])
        mf = np.array([mlp[s]["phase2"]["test"]["macro_f1"] for s in seeds])
        bf = np.array([baseline[s]["phase2"]["test"]["macro_f1"] for s in seeds])
        pa = np.array([pqc[s]["phase2"]["test"]["auc"] for s in seeds])
        ma = np.array([mlp[s]["phase2"]["test"]["auc"] for s in seeds])
        delta = mf - pf

        ap_p, ap_m = [], []
        for seed in seeds:
            labels = np.asarray(pqc[seed]["test_labels"])
            assert labels.tolist() == mlp[seed]["test_labels"]
            ap_p.append(average_precision_score(labels, pqc[seed]["test_logits"]))
            ap_m.append(average_precision_score(labels, mlp[seed]["test_logits"]))
        ap_p, ap_m = np.asarray(ap_p), np.asarray(ap_m)

        item = item_cell(pqc, mlp, seeds, task)
        rows.append({
            "task": task,
            "n": len(seeds),
            "pqc_effective_params": 24,
            "mlp_trainable_params": 23,
            "pqc_macro_f1": float(pf.mean()),
            "pqc_macro_f1_sd": float(pf.std(ddof=1)),
            "mlp_macro_f1": float(mf.mean()),
            "mlp_macro_f1_sd": float(mf.std(ddof=1)),
            "original_mlp_macro_f1": float(bf.mean()),
            "delta_macro_f1": float(delta.mean()),
            "paired_ci95": paired_ci(delta),
            "paired_t_p": float(stats.ttest_rel(mf, pf).pvalue),
            "wilcoxon_p": float(stats.wilcoxon(delta).pvalue),
            "delta_auc": float((ma - pa).mean()),
            "paired_t_p_auc": float(stats.ttest_rel(ma, pa).pvalue),
            "delta_ap": float((ap_m - ap_p).mean()),
            "paired_t_p_ap": float(stats.ttest_rel(ap_m, ap_p).pvalue),
            "mlp_h2_vs_h3_p": float(stats.ttest_rel(mf, bf).pvalue),
            "item_perm_p": item["perm_p"],
            "item_hier_ci95": item["hier_boot_ci95"],
        })

    adjusted = holm([row["paired_t_p"] for row in rows])
    for row, value in zip(rows, adjusted):
        row["paired_t_p_holm3"] = float(value)

    os.makedirs(os.path.join(ROOT, "results"), exist_ok=True)
    os.makedirs(os.path.join(ROOT, "paper"), exist_ok=True)
    json.dump(rows, open(os.path.join(ROOT, "results/stats_effective_match_v10.json"), "w"), indent=1)

    task = {"mrpc": r"\MRPC{}", "paws": r"\PAWS{}", "qqp": r"\QQP{}"}
    lines = [
        "%% Auto-generated by scripts/stats_effective_match_v10.py -- do not hand-edit.",
        r"\begin{table}[H]",
        r"\centering",
        r"\caption{Reviewer-requested effective-parameter control (depthwise reducer, $q = 8$, eight seeds). The calibrated \PQC{} has 24 output-relevant parameters (22 circuit plus 2 affine); the hidden-width-2 calibrated \MLP{} has 23 trainable parameters. $\Delta$ is \MLP{}$-$\PQC{} macro F1. $p_{\mathrm{pair}}$ is a paired $t$-test across seeds and $p_{\mathrm{Holm}}$ its correction over these three reviewer-requested cells. The item-level permutation treats the development item as the sampling unit, as in Appendix~A. $\Delta$AUC and $\Delta$AP are threshold-free differences.}",
        r"\label{tab:effective_match_v10}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lcccccccccc}",
        r"\toprule",
        r"Task & PQC macro F1 & MLP(2) macro F1 & $\Delta$ & 95\% CI & $p_{\mathrm{pair}}$ & $p_{\mathrm{Holm}}$ & item $p$ & $\Delta$AUC ($p$) & $\Delta$AP ($p$) & MLP(2) vs MLP(3) $p$ \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(
            f'{task[row["task"]]} & '
            f'${row["pqc_macro_f1"]:.4f} \\pm {row["pqc_macro_f1_sd"]:.4f}$ & '
            f'${row["mlp_macro_f1"]:.4f} \\pm {row["mlp_macro_f1_sd"]:.4f}$ & '
            f'${row["delta_macro_f1"]:+.4f}$ & '
            f'$[{row["paired_ci95"][0]:+.4f}, {row["paired_ci95"][1]:+.4f}]$ & '
            f'${row["paired_t_p"]:.4f}$ & ${row["paired_t_p_holm3"]:.4f}$ & '
            f'${row["item_perm_p"]:.4f}$ & '
            f'${row["delta_auc"]:+.4f}$ (${row["paired_t_p_auc"]:.4f}$) & '
            f'${row["delta_ap"]:+.4f}$ (${row["paired_t_p_ap"]:.4f}$) & '
            f'${row["mlp_h2_vs_h3_p"]:.4f}$ \\\\'
        )
    lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
    open(os.path.join(ROOT, "paper/table_effective_match_v10.tex"), "w").write("\n".join(lines) + "\n")

    for row in rows:
        print(
            f'{row["task"]:<5} gap {row["delta_macro_f1"]:+.4f} '
            f'paired {row["paired_t_p"]:.4f} Holm3 {row["paired_t_p_holm3"]:.4f} '
            f'item {row["item_perm_p"]:.4f} dAUC {row["delta_auc"]:+.4f} '
            f'dAP {row["delta_ap"]:+.4f} h2-v-h3 {row["mlp_h2_vs_h3_p"]:.4f}'
        )
    print("wrote results/stats_effective_match_v10.json and paper/table_effective_match_v10.tex")


if __name__ == "__main__":
    main()
